name: Build GOLDbridge APK
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build APK
        uses: simple-apps/github-action-web-to-apk@v1.0.0
        with:
          app_name: "GOLDbridge"
          url: "https://philipsjerome402-bit.github.io/GOLDbridge/"
          icon: "logo.png"
          
